import { useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';
import { StatusBar as ExpoStatusBar } from 'expo-status-bar';

type Mode = 'EDITOR' | 'COMPONENTES' | 'SIMULAR';
type BlockType = 'NO' | 'NC' | 'COIL';
type Block = { id: string; type: BlockType; address: string };
type Branch = { id: string; blocks: Block[]; coil?: Block };
type Rung = { id: string; series: Block[]; branches: Branch[]; coil?: Block };
type Zone = { kind: 'series'; rungId: string; index: number } | { kind: 'branch'; rungId: string; branchId: string; index: number } | { kind: 'coil'; rungId: string };
type PlcState = Record<string, boolean>;

const inputs = ['I0.0', 'I0.1', 'I0.2', 'I0.3', 'I0.4', 'I0.5'];
const outputs = ['Q0.0', 'Q0.1', 'Q0.2', 'M0.0'];

function uid(prefix: string) { return `${prefix}-${Date.now()}-${Math.round(Math.random() * 9999)}`; }
function initialRungs(): Rung[] { return [{ id: 'rung-1', series: [{ id: 'i00', type: 'NO', address: 'I0.0' }, { id: 'i01', type: 'NC', address: 'I0.1' }], branches: [{ id: 'branch-1', blocks: [{ id: 'i02', type: 'NO', address: 'I0.2' }] }], coil: { id: 'q00', type: 'COIL', address: 'Q0.0' } }, { id: 'rung-2', series: [{ id: 'i03', type: 'NO', address: 'I0.3' }, { id: 'i04', type: 'NO', address: 'I0.4' }], branches: [{ id: 'branch-2', blocks: [], coil: { id: 'm00', type: 'COIL', address: 'M0.0' } }], coil: { id: 'q01', type: 'COIL', address: 'Q0.1' } }]; }
function clone(rungs: Rung[]): Rung[] { return rungs.map((r) => ({ ...r, series: r.series.map((b) => ({ ...b })), branches: r.branches.map((br) => ({ ...br, blocks: br.blocks.map((b) => ({ ...b })), coil: br.coil ? { ...br.coil } : undefined })), coil: r.coil ? { ...r.coil } : undefined })); }
function isClosed(block: Block, state: PlcState) { if (block.type === 'NO') return Boolean(state[block.address]); if (block.type === 'NC') return !Boolean(state[block.address]); return Boolean(state[block.address]); }
function evaluate(rungs: Rung[], state: PlcState) { const next = { ...state }; const activeBlocks: Record<string, boolean> = {}; const activeRungs: Record<string, boolean> = {}; rungs.forEach((r) => { const seriesPower = r.series.every((b) => { const p = isClosed(b, next); activeBlocks[b.id] = p; return p; }); const branchPower = r.branches.some((br) => { const p = br.blocks.length ? br.blocks.every((b) => isClosed(b, next)) : seriesPower; br.blocks.forEach((b) => { activeBlocks[b.id] = p; }); if (br.coil) { activeBlocks[br.coil.id] = p; next[br.coil.address] = p; } return p; }); const power = seriesPower || branchPower; activeRungs[r.id] = power; if (r.coil) { activeBlocks[r.coil.id] = power; next[r.coil.address] = power; } }); return { state: next, activeBlocks, activeRungs }; }
function nextBlock(type: BlockType, rungs: Rung[]): Block { const used = new Set<string>(); rungs.forEach((r) => { r.series.forEach((b) => used.add(b.address)); r.branches.forEach((br) => { br.blocks.forEach((b) => used.add(b.address)); if (br.coil) used.add(br.coil.address); }); if (r.coil) used.add(r.coil.address); }); if (type === 'COIL') return { id: uid('coil'), type, address: outputs.find((o) => !used.has(o)) ?? 'Q0.0' }; return { id: uid('in'), type, address: inputs.find((i) => !used.has(i)) ?? 'I0.0' }; }

export function SimurelayStyleLadderScreenV2() {
  const [mode, setMode] = useState<Mode>('EDITOR');
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [ioOpen, setIoOpen] = useState(false);
  const [activeTool, setActiveTool] = useState<BlockType | null>(null);
  const [rungs, setRungs] = useState<Rung[]>(() => initialRungs());
  const [state, setState] = useState<PlcState>({ 'I0.0': true, 'I0.1': false, 'I0.2': true, 'I0.3': true, 'I0.4': true, 'I0.5': false, 'Q0.0': false, 'Q0.1': false, 'Q0.2': false, 'M0.0': false });
  const scan = useMemo(() => evaluate(rungs, state), [rungs, state]);
  const isSimulating = mode === 'SIMULAR';

  function chooseTool(type: BlockType) { setActiveTool(type); setMode('EDITOR'); setDrawerOpen(false); }
  function setSimulate() { setMode('SIMULAR'); setDrawerOpen(false); setIoOpen(false); setActiveTool(null); setState((current) => evaluate(rungs, current).state); }
  function toggleInput(address: string) { const next = { ...state, [address]: !Boolean(state[address]) }; setState(isSimulating ? evaluate(rungs, next).state : next); }
  function addRung() { setRungs((current) => [...current, { id: uid('rung'), series: [], branches: [], coil: undefined }]); }
  function addBranch(rungId: string) { setRungs((current) => current.map((r) => r.id === rungId ? { ...r, branches: [...r.branches, { id: uid('branch'), blocks: [nextBlock('NO', current)] }] } : r)); }

  function insertAt(zone: Zone) {
    if (!activeTool || isSimulating) return;
    const next = clone(rungs);
    const rung = next.find((r) => r.id === zone.rungId);
    if (!rung) return;
    if (zone.kind === 'coil') rung.coil = nextBlock('COIL', next);
    if (zone.kind === 'series' && activeTool !== 'COIL') rung.series.splice(zone.index, 0, nextBlock(activeTool, next));
    if (zone.kind === 'branch' && activeTool !== 'COIL') {
      const branch = rung.branches.find((br) => br.id === zone.branchId);
      if (branch) branch.blocks.splice(zone.index, 0, nextBlock(activeTool, next));
    }
    setRungs(next);
    setActiveTool(null);
  }

  return <SafeAreaView style={styles.safeArea}><ExpoStatusBar style="light" /><StatusBar barStyle="light-content" /><View style={styles.root}>
    <View style={styles.header}><Pressable style={styles.iconButton}><Text style={styles.iconText}>☰</Text></Pressable><View style={styles.titleBox}><Text style={styles.title}>CLP Fácil</Text><Text style={styles.subtitle}>{activeTool ? `inserindo ${activeTool}` : 'untitled'}</Text></View><Pressable style={styles.iconButton}><Text style={styles.iconText}>▣</Text></Pressable><Pressable style={styles.simulateButton} onPress={setSimulate}><Text style={styles.simulateIcon}>▶</Text><Text style={styles.simulateText}>SIMULAR</Text></Pressable><Pressable style={styles.iconButton}><Text style={styles.iconText}>⋮</Text></Pressable></View>
    <View style={styles.tabs}><TabButton label="EDITOR" active={mode === 'EDITOR'} onPress={() => setMode('EDITOR')} /><TabButton label="COMPONENTES" active={mode === 'COMPONENTES'} onPress={() => { setMode('COMPONENTES'); setDrawerOpen(true); }} /><TabButton label="SIMULAR" active={mode === 'SIMULAR'} onPress={setSimulate} /></View>
    <View style={styles.workspace}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.canvasX}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.canvasY}><View style={styles.canvas}><Grid /><View style={styles.leftRail} /><View style={styles.rightRail} />{rungs.map((rung, index) => <RungView key={rung.id} rung={rung} index={index + 1} active={Boolean(scan.activeRungs[rung.id])} activeBlocks={scan.activeBlocks} zonesVisible={Boolean(activeTool) && !isSimulating} onDrop={insertAt} onAddBranch={addBranch} />)}<Pressable style={styles.addRungLine} onPress={addRung}><Text style={styles.addRungText}>+ Rung</Text></Pressable></View></ScrollView></ScrollView>{drawerOpen ? <ComponentDrawer onClose={() => setDrawerOpen(false)} onChoose={chooseTool} /> : null}{!isSimulating ? <Pressable style={styles.fab} onPress={() => setDrawerOpen((c) => !c)}><Text style={styles.fabText}>＋</Text></Pressable> : null}<Pressable style={styles.bottomHandle} onPress={() => setIoOpen((c) => !c)}><Text style={styles.bottomHandleText}>{ioOpen ? '⌄' : '⌃'}</Text></Pressable></View>
    {ioOpen ? <View style={styles.ioSheet}><View style={styles.sheetHandle} /><View style={styles.sheetTabs}><Text style={styles.sheetTabActive}>I/O</Text><Text style={styles.sheetTab}>ESTADO</Text><Pressable onPress={() => setIoOpen(false)}><Text style={styles.sheetClose}>⌄</Text></Pressable></View><View style={styles.ioContent}><View style={styles.ioColumn}><Text style={styles.ioTitle}>ENTRADAS</Text>{inputs.slice(0, 4).map((input) => <Pressable key={input} style={styles.ioRow} onPress={() => toggleInput(input)}><Text style={styles.ioLabel}>{input}</Text><View style={[styles.dot, state[input] && styles.dotOn]} /><View style={[styles.switchTrack, state[input] && styles.switchTrackOn]}><View style={[styles.switchThumb, state[input] && styles.switchThumbOn]} /></View></Pressable>)}</View><View style={styles.ioDivider} /><View style={styles.ioColumn}><Text style={styles.ioTitle}>SAÍDAS</Text>{outputs.slice(0, 3).map((output) => <View key={output} style={styles.ioRow}><Text style={styles.ioLabel}>{output}</Text><View style={[styles.dot, scan.state[output] && styles.dotOn]} /><Text style={[styles.lamp, scan.state[output] && styles.lampOn]}>●</Text></View>)}</View></View></View> : null}
  </View></SafeAreaView>;
}

function TabButton({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable style={styles.tabButton} onPress={onPress}><Text style={[styles.tabText, active && styles.tabTextActive]}>{label}</Text>{active ? <View style={styles.tabLine} /> : null}</Pressable>; }
function Grid() { return <View style={styles.grid}>{Array.from({ length: 260 }).map((_, i) => <View key={i} style={styles.gridCell} />)}</View>; }
function DropZone({ visible, onPress }: { visible: boolean; onPress: () => void }) { return visible ? <Pressable style={styles.dropZone} onPress={onPress}><Text style={styles.dropZoneText}>+</Text></Pressable> : <View style={styles.hiddenZone} />; }
function RungView({ index, rung, active, activeBlocks, zonesVisible, onDrop, onAddBranch }: { index: number; rung: Rung; active: boolean; activeBlocks: Record<string, boolean>; zonesVisible: boolean; onDrop: (zone: Zone) => void; onAddBranch: (rungId: string) => void }) { const top = 215 + (index - 1) * 325; return <View style={[styles.rung, { top }]}><Text style={styles.rungNumber}>{index}</Text><View style={[styles.rungWire, active && styles.wireLive]} /><View style={styles.rungRow}><DropZone visible={zonesVisible} onPress={() => onDrop({ kind: 'series', rungId: rung.id, index: 0 })} />{rung.series.map((block, i) => <View key={block.id} style={styles.inline}><BlockView block={block} active={Boolean(activeBlocks[block.id])} /><DropZone visible={zonesVisible} onPress={() => onDrop({ kind: 'series', rungId: rung.id, index: i + 1 })} /></View>)}<View style={[styles.fillWire, active && styles.wireLive]} />{rung.coil ? <BlockView block={rung.coil} active={Boolean(activeBlocks[rung.coil.id])} /> : <DropZone visible={zonesVisible} onPress={() => onDrop({ kind: 'coil', rungId: rung.id })} />}</View>{rung.branches.map((branch, branchIndex) => <View key={branch.id} style={[styles.branch, branchIndex > 0 && styles.branchLower]}><DropZone visible={zonesVisible} onPress={() => onDrop({ kind: 'branch', rungId: rung.id, branchId: branch.id, index: 0 })} />{branch.blocks.map((block, i) => <View key={block.id} style={styles.inline}><BlockView block={block} active={Boolean(activeBlocks[block.id])} /><DropZone visible={zonesVisible} onPress={() => onDrop({ kind: 'branch', rungId: rung.id, branchId: branch.id, index: i + 1 })} /></View>)}{branch.coil ? <BlockView block={branch.coil} active={Boolean(activeBlocks[branch.coil.id])} /> : null}</View>)}{zonesVisible ? <Pressable style={styles.branchFab} onPress={() => onAddBranch(rung.id)}><Text style={styles.branchFabText}>+R</Text></Pressable> : null}</View>; }
function BlockView({ block, active }: { block: Block; active: boolean }) { return <View style={styles.blockWrap}><Text style={[styles.blockLabel, active && styles.liveText]}>{block.address}</Text><Text style={[block.type === 'COIL' ? styles.coilSymbol : styles.contactSymbol, active && styles.liveText]}>{block.type === 'COIL' ? '( )' : block.type === 'NO' ? '| |' : '|/|'}</Text></View>; }
function ComponentDrawer({ onClose, onChoose }: { onClose: () => void; onChoose: (type: BlockType) => void }) { return <View style={styles.drawer}><View style={styles.drawerHeader}><Text style={styles.drawerTitle}>COMPONENTES</Text><Pressable onPress={onClose}><Text style={styles.drawerClose}>×</Text></Pressable></View><View style={styles.componentList}><Pressable onPress={() => onChoose('NO')}><MiniComponent label="NA" icon="| |" /></Pressable><Pressable onPress={() => onChoose('NC')}><MiniComponent label="NF" icon="|/|" /></Pressable><Pressable onPress={() => onChoose('COIL')}><MiniComponent label="Coil" icon="( )" /></Pressable></View><Text style={styles.drawerHint}>Escolha um componente e toque em uma zona + no canvas.</Text></View>; }
function MiniComponent({ label, icon }: { label: string; icon: string }) { return <View style={styles.miniComponent}><Text style={styles.miniIcon}>{icon}</Text><Text style={styles.miniLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#111' }, root: { flex: 1, backgroundColor: '#111' }, header: { height: 88, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#111' }, iconButton: { minWidth: 34, minHeight: 44, alignItems: 'center', justifyContent: 'center' }, iconText: { color: '#f5f5f5', fontSize: 30, fontWeight: '800' }, titleBox: { flex: 1 }, title: { color: '#f8f8f8', fontSize: 20, fontWeight: '900' }, subtitle: { color: '#cfcfcf', fontSize: 15, marginTop: 2 }, simulateButton: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 8, minHeight: 44 }, simulateIcon: { color: '#18a34a', fontSize: 24, fontWeight: '900' }, simulateText: { color: '#28a745', fontSize: 15, fontWeight: '900' },
  tabs: { height: 64, flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#2f2f2f', backgroundColor: '#111' }, tabButton: { flex: 1, alignItems: 'center', justifyContent: 'center' }, tabText: { color: '#9a9a9a', fontSize: 16, fontWeight: '900', letterSpacing: 1 }, tabTextActive: { color: '#20b44b' }, tabLine: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 4, backgroundColor: '#20b44b' },
  workspace: { flex: 1, overflow: 'hidden', backgroundColor: '#121212' }, canvasX: { minWidth: 780, flexGrow: 1 }, canvasY: { minHeight: 1100, flexGrow: 1 }, canvas: { width: 820, height: 1100, position: 'relative', backgroundColor: '#121212' }, grid: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, flexDirection: 'row', flexWrap: 'wrap' }, gridCell: { width: 41, height: 41, borderRightWidth: 1, borderBottomWidth: 1, borderColor: '#242424' }, leftRail: { position: 'absolute', left: 58, top: 90, bottom: 150, width: 3, backgroundColor: '#e9e9e9' }, rightRail: { position: 'absolute', right: 58, top: 90, bottom: 150, width: 3, backgroundColor: '#e9e9e9' },
  rung: { position: 'absolute', left: 58, right: 58, height: 260 }, rungNumber: { position: 'absolute', left: -36, top: 54, color: '#969696', fontSize: 17 }, rungWire: { position: 'absolute', left: 0, right: 0, top: 68, height: 3, backgroundColor: '#e9e9e9' }, wireLive: { backgroundColor: '#42c95b' }, rungRow: { position: 'absolute', left: 100, right: 100, top: 16, height: 106, flexDirection: 'row', alignItems: 'center', gap: 35 }, inline: { flexDirection: 'row', alignItems: 'center', gap: 35 }, fillWire: { flex: 1, height: 3, minWidth: 20, backgroundColor: '#e9e9e9' }, branch: { position: 'absolute', left: 250, right: 150, top: 118, height: 80, borderLeftWidth: 3, borderBottomWidth: 3, borderRightWidth: 3, borderColor: '#e9e9e9', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 35 }, branchLower: { top: 170 }, branchFab: { position: 'absolute', right: 82, bottom: 18, borderWidth: 1, borderColor: '#28a745', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6 }, branchFabText: { color: '#28a745', fontWeight: '900' },
  blockWrap: { minWidth: 74, alignItems: 'center', justifyContent: 'center' }, blockLabel: { color: '#27b34a', fontSize: 19, fontWeight: '900', marginBottom: 8 }, liveText: { color: '#51dc69' }, contactSymbol: { color: '#f2f2f2', fontSize: 45, fontWeight: '300', lineHeight: 50 }, coilSymbol: { color: '#f2f2f2', fontSize: 48, fontWeight: '300', lineHeight: 50 }, dropZone: { width: 28, height: 28, borderRadius: 999, borderWidth: 1, borderColor: '#28a745', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(40,167,69,0.16)' }, dropZoneText: { color: '#28a745', fontSize: 21, fontWeight: '900' }, hiddenZone: { width: 0, height: 28 },
  drawer: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 360, backgroundColor: '#151515', borderRightWidth: 1, borderColor: '#292929', zIndex: 5, paddingBottom: 20 }, drawerHeader: { height: 58, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, drawerTitle: { color: '#eee', fontWeight: '900', letterSpacing: 1 }, drawerClose: { color: '#eee', fontSize: 32 }, componentList: { padding: 18, flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, drawerHint: { color: '#aaa', paddingHorizontal: 20, fontSize: 13 }, miniComponent: { width: 96, height: 92, borderWidth: 1, borderColor: '#333', alignItems: 'center', justifyContent: 'center', backgroundColor: '#1e1e1e' }, miniIcon: { color: '#f1f1f1', fontSize: 32 }, miniLabel: { color: '#ddd', fontSize: 12, marginTop: 8 },
  fab: { position: 'absolute', right: 30, bottom: 58, width: 76, height: 76, borderRadius: 38, backgroundColor: '#28a745', alignItems: 'center', justifyContent: 'center', elevation: 10 }, fabText: { color: '#fff', fontSize: 44, lineHeight: 50 }, bottomHandle: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 44, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(17,17,17,0.92)' }, bottomHandleText: { color: '#fff', fontSize: 28, fontWeight: '900' }, addRungLine: { position: 'absolute', left: 165, right: 165, top: 890, borderWidth: 1, borderColor: '#2e8b47', borderStyle: 'dashed', borderRadius: 999, height: 48, alignItems: 'center', justifyContent: 'center' }, addRungText: { color: '#37bf4b', fontWeight: '900' },
  ioSheet: { backgroundColor: '#171717', borderTopLeftRadius: 26, borderTopRightRadius: 26, borderWidth: 1, borderColor: '#303030', paddingBottom: 18, paddingHorizontal: 24 }, sheetHandle: { alignSelf: 'center', width: 72, height: 8, borderRadius: 999, backgroundColor: '#707070', marginTop: 10, marginBottom: 18 }, sheetTabs: { height: 46, flexDirection: 'row', alignItems: 'center', gap: 36 }, sheetTabActive: { color: '#2ab84a', fontSize: 18, fontWeight: '900' }, sheetTab: { color: '#8d8d8d', fontSize: 18, fontWeight: '900', flex: 1 }, sheetClose: { color: '#fff', fontSize: 28, fontWeight: '900' }, ioContent: { flexDirection: 'row', paddingTop: 20, minHeight: 210 }, ioColumn: { flex: 1 }, ioDivider: { width: 1, backgroundColor: '#343434', marginHorizontal: 24 }, ioTitle: { color: '#fff', fontSize: 16, fontWeight: '900', marginBottom: 14 }, ioRow: { height: 42, flexDirection: 'row', alignItems: 'center', gap: 16 }, ioLabel: { color: '#f2f2f2', fontSize: 19, fontWeight: '700', width: 52 }, dot: { width: 14, height: 14, borderRadius: 7, backgroundColor: '#666' }, dotOn: { backgroundColor: '#37bf4b' }, switchTrack: { width: 62, height: 32, borderRadius: 999, backgroundColor: '#2c2c2c', borderWidth: 1, borderColor: '#626262', padding: 2, marginLeft: 'auto' }, switchTrackOn: { backgroundColor: '#2aa846' }, switchThumb: { width: 26, height: 26, borderRadius: 13, backgroundColor: '#8d8d8d' }, switchThumbOn: { backgroundColor: '#fff', transform: [{ translateX: 30 }] }, lamp: { fontSize: 30, color: '#686868', marginLeft: 'auto' }, lampOn: { color: '#37bf4b' },
});
